config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :dogs do
    resources :likes, only: [:create]
  end
  root to: "dogs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_many_attached :images
  belongs_to :user
  has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :dog
    belongs_to :user
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :dogs
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  DOGS_PER_PAGE = 5

  # GET /dogs
  # GET /dogs.json
  def index
    # @dogs = Dog.all
    @page = params.fetch(:page, 1).to_i
    if params[:sort_by_likes]
      @dogs = Dog.left_joins(:likes).group("id").order("count(likes.id) desc, likes.created_at desc")
      .offset((@page-1) * DOGS_PER_PAGE).limit(DOGS_PER_PAGE)
    else
      @dogs = Dog.offset((@page-1) * DOGS_PER_PAGE).limit(DOGS_PER_PAGE)
    end
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
    redirect_to dogs_path if current_user != @dog.user
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)
    @dog.user = current_user

    respond_to do |format|
      if @dog.save
        @dog.images.attach(params[:dog][:images]) if params[:dog][:images].present?
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        @dog.images.attach(params[:dog][:images]) if params[:dog][:images].present?

        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_dog
    @dog = Dog.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dog_params
    params.require(:dog).permit(:name, :description, images: [])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :set_dog

    def create
        if current_user === @dog.user
            redirect_to dogs_path, notice: "can't like your own dog"
            return
        end

        @dog.likes.where(user_id: current_user.id).first_or_create
        respond_to do |format|
            format.html { redirect_to dogs_path }
        end
    end

    private

    def set_dog
        @dog = Dog.find(params[:dog_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/dogs/_form.html.erb
<%= simple_form_for @dog do |f| %>
  <%= f.input :name %>
  <%= f.input :description, as: :text %>
  <%= f.file_field :images, accept: 'image/png,image/gif,image/jpeg,image/jpg', multiple: true %>

  <% if @dog.images.any? %>
    <%= image_tag @dog.images.first %>
  <% end %>

  <%= f.button :submit %>
<% end %>

app/views/dogs/_thumbnail.html.erb
<a href="<%= url_for(dog) %>">
  <article>
    <h2 class="dog-name"><%= dog.name %></h2>
    <%= image_tag url_for(dog.images.first), class: "dog-photo", alt: "Photo of #{dog.name}" %>
  </article>
</a>
<%= link_to "Like", dog_likes_path(dog), method: :post %>

<div>
  <%= image_tag("ad.jpg", width: 100) if dog.id.even?%> 
</div>

app/views/dogs/edit.html.erb
<h1>Edit Your Dog</h1>
<%= render partial: 'form' %>

app/views/dogs/index.html.erb
<%= link_to "sort by likes in last hour", dogs_path(sort_by_likes: true) %>

<%= render partial: 'thumbnail', collection: @dogs, as: :dog %>

<div style="display: flex; align-items: center">
    <% unless @page === 1 %>
        <%= link_to "Previous Page", dogs_path(page: @page - 1) %>
    <% end %>

    <p><%= @page %></p>
    <%= link_to "Next Page", dogs_path(page: @page + 1) %>
</div>

app/views/dogs/new.html.erb
<h1>Add Your Dog</h1>
<%= render partial: 'form' %>

app/views/dogs/show.html.erb
<section>
  <h2><%= @dog.name %></h2>

  <% @dog.images.each do |image| %>
    <%= image_tag url_for(image), alt: "Photo of #{@dog.name}" %>
  <% end %>

  <p><%= @dog.description %></p>

  <% if current_user === @dog.user %>
    <%= link_to "Edit #{@dog.name}'s Profile", edit_dog_path %>
    <br>
    <%= link_to "Delete #{@dog.name}'s Profile", dog_path, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogProfile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div id="layout">
      <header>
        <h1><%= link_to 'Dog Profile Demo', root_path %></h1>
        <div class="actions">
          <% if current_user %>
            <%= link_to 'Add your dog', new_dog_path %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Sign in', new_user_session_path %>
            <%= link_to 'Sign up', new_user_registration_path %>
          <% end %>
        </div>
      </header>
      <div id="main">
        <div class="notifications">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
        <%= yield %>
      </div>
      <div class="footer"></div>
    </div>

  </body>
</html>